using System;
using VideoOS.Platform.DriverFramework.Definitions;

namespace SampleDeviceDriver
{
    public static class Constants
    {
        public static readonly ProductDefinition Product1 = new ProductDefinition
        {
            Id = new Guid("6ea27d79-b57d-498a-977f-d99bb3d8d639"),
            Name = "My SampleDeviceDriver"
        };

        public static readonly Guid DriverId = new Guid("dd2bc6ee-644a-465a-9586-e7bad47333e8");

        public static readonly Guid Audio1 = new Guid("d0d67a7a-e2f6-44c3-9fa1-d437e6856302");
        public static readonly Guid Video1 = new Guid("6f4f9cd3-05f3-4ae8-bb1e-b4977f2a449e");
        public static readonly Guid Input1 = new Guid("1671678b-e8d2-4fe7-a2da-5059967fa2c9");
        public static readonly Guid Metadata1 = new Guid("f877f660-4f40-4ffc-955c-5e15042e3784");
        public static readonly Guid Output1 = new Guid("79d8d6a8-0cbc-4d82-853b-ba696d23d94a");
        public static readonly Guid Speaker1 = new Guid("dabf8b98-7df9-484b-8052-99c960150035");

        public static readonly Guid VideoStream1RefId = new Guid("d485fa50-5943-436f-9f4d-94e8a99c6e94");
        public static readonly Guid AudioStream1RefId = new Guid("580c6f4f-7cad-4af5-8ade-94861129cea8");
        public static readonly Guid SpeakerStream1RefId = new Guid("AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA"); // TODO: Due to shortcoming in Visual Studio only up to 10 GUIDs can be auto-generated by template. Please replace this one with a newly generated unique ID.
    }
}
